print("Introduzca el intante 1")
h1 = int(input("Hora: "))
m1 = int(input("Minuto: ")) 
s1 = int(input("Segundo: "))
print("Introduzca el intante 2")
h2 = int(input("Hora: "))
m2 = int(input("Minuto: ")) 
s2 = int(input("Segundo: "))
