nombre = input("Nombre: ")
apellido1 = input("Primer apellido: ")
apellido2 = input("Segundo apellido: ") 
print("Nombre completo: {} {} {}".format(nombre, apellido1, apellido2))
print("Al reves: {} {} {}".format(apellido2, apellido1, nombre))
print(nombre) 
print(apellido1) 
print(apellido2) 
